[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[81;5u"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[80;6u"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[82;6u"
key = "R"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[69;6u"
key = "E"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[70;6u"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[84;6u"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[env]
TERM = "screen-256color"

[font]
size = 12

[font.bold]
family = "MesloLGSDZ Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGSDZ Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGSDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[keyboard]
